### ISSUE TITLE
Internet connection lost, or server unreachable

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#216]
`requests` exception is (rightfully) mouthfull, when a user machine loose all internet connectivity, or when a ser does a typo in a hostname, it'll lead to:

- socket.gaierror: Name or service not known, causing
- urllib3.exceptions.NewConnectionError, causing retries, leading to
- urllib3.exceptions.MaxRetryError
- leading finally to requests' `ConnectionError`.

To match it, I friendly has to match both the `ConnectionError` and the socket.gaierror's `Name or service not known`, to avoid catching other near errors, having different meanings.

Message could look like:

> The server you're trying to join can't be joined. Check for typos in the URL, and check your internet connectivity.

```
## Exception Python


    :::pytb
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known

        During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
        chunked=chunked,
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
        self._validate_conn(conn)
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
        conn.connect()
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 353, in connect
        conn = self._new_conn()
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
        self, "Failed to establish a new connection: %s" % e
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff9cac660f0>: Failed to establish a new connection: [Errno -2] Name or service not known

        During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/python (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9cac660f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

        During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "solution.py", line 6, in <module>
        r = requests.get('https://api.github.com/users/python')
      File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 76, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/python (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9cac660f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))



Aucune information n’est connue à propos de cette exception.
Veuillez signaler cet exemple à
https://github.com/aroberge/friendly-traceback/issues

Si vous utilisez la console Friendly, utilisez `www()` pour
faire une recherche sur Internet pour ce cas particulier.



### L'exécution s'est arrêtée à la ligne 6 du fichier solution.py



    :::text
           4: # But you may run this on your computer.
           5: import requests
        -->6: r = requests.get('https://api.github.com/users/python')
           7: if(r.status_code!=200):



    :::text
        requests: <module requests> from FRIENDLY:/requests/__init__.py



### Exception levée à la ligne 516 du fichier FRIENDLY:/requests/adapters.py.



    :::text
           514:                 raise SSLError(e, request=request)
           515: 
        -->516:             raise ConnectionError(e, request=request)



    :::text
        request: <PreparedRequest [GET]>
        global ConnectionError: <class requests.exceptions.ConnectionError>
```

**Comment by aroberge** [comment]
Quick first thoughts:

I'm thinking of doing something like the following hand-waving approach:
```python
if issubclass(exception, OSError):
    if 'socket' in sys.modules and issubclass(exception, socket.error):
        return handle_socket_error(exception)
    elif issubclass(exception, ConnectionError):
        return handle_connection_error(exception)
    else:
        return handle_generic_os_error(exception)
```

I *think* that I handle exception by catching the first type (`socket.gaierror` in your example) and not the last one when there a chain of exceptions.

I suspect that, for most users of friendly, in both `ConnectionError` and `socket.error`, making a general suggestion, similar to the one you wrote:

> I suspect that you are trying to connect to a server and a connection cannot be made.
> If that is the case, check for typos in the URL and check your internet connectivity.

would likely be sufficient for now.

Over time, I could refine the message as I get more specific examples. For now, I would check specifically for the one you gave
(`Name or service not known`) and see if it deserves to get a more specific suggestion.

**Comment by aroberge** [comment]
I have what I believe is a satisfactory working implementation.  You can view the result of a test at https://aroberge.github.io/friendly-traceback-docs/docs/html/tracebacks_en_3.8.html#urllib-error

If you look closely, you will see that some lines are skipped and that many paths are much shorter than your original report. This is because I show `"shortened_traceback"` instead of `"simulated_python_traceback"` as you do in correction_helper: https://github.com/JulienPalard/correction-helper/blob/ef121836267d265fadcd36dda2f31b947be9b2ad/correction_helper.py#L190

I **strongly** suggest that you do the same: I think that you will like the result better.  (If you do so, lines 217 and 218 could also be deleted ... actually, they haven't done anything for quite a while by now as I no longer prepend with "Simulated".)

If you are not (yet) convinced, I suggest you try the following both using a normal Python interpreter AND HackInScience as it is currently:

```python
def a():
   b()
def b():
   a()

a()
```

In both cases, you will likely see a traceback that is something like 2000 lines long.

If you use friendly to run this program, you will see something like the following:
```python
>>> def a():
...    b()
...
>>> def b():
...    a()
...
>>> a()

Traceback (most recent call last):
  File "<friendly-console:3>", line 1, in <module>
    a()

       ... More lines not shown. ...

  File "<friendly-console:2>", line 2, in b
    a()
  File "<friendly-console:1>", line 2, in a
    b()
  File "<friendly-console:2>", line 2, in b
    a()
RecursionError: maximum recursion depth exceeded
```

**Comment by JulienPalard** [comment]
> I strongly suggest that you do the same

Time to migrate from friendly-traceback to friendly at the same time, then. Thanks for the recommandations!

**Comment by aroberge** [comment]
This issue is not handled correctly - no specific information is given.

**Comment by aroberge** [comment]
Should be working properly now - friendly version 0.3.60 uploaded to PyPI.

**Comment by aroberge** [comment]
@JulienPalard With a change I just made, the full "friendly traceback" shown to the user is now greatly simplified.

Before:
```python
Traceback (most recent call last):
  File "PYTHON_LIB:\urllib\request.py", line 1346, in do_open
       ... More lines not shown. ...
  File "PYTHON_LIB:\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "PYTHON_LIB:\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TESTS:\runtime\test_os_error.py", line 8, in test_Urllib_error
    request.urlopen("http://does_not_exist")
       ... More lines not shown. ...
  File "PYTHON_LIB:\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "PYTHON_LIB:\urllib\request.py", line 1349, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

An exception of type `URLError` is a subclass of `OSError`.
An `OSError` exception is usually raised by the Operating System
to indicate that an operation is not allowed or that
a resource is not available.

I suspect that you are trying to connect to a server and
that a connection cannot be made.

If that is the case, check for typos in the URL
and check your internet connectivity.

Execution stopped on line 8 of file TESTS:\runtime\test_os_error.py.

   5: def test_Urllib_error():
   6:     from urllib import request, error
   7:     try:
-->8:         request.urlopen("http://does_not_exist")
   9:     except error.URLError as e:

        request:  <module urllib.request> from PYTHON_LIB:\urllib\request.py
        request.urlopen:  <function urlopen>

Exception raised on line 1349 of file PYTHON_LIB:\urllib\request.py.

   1345:             try:
   1346:                 h.request(req.get_method(), req.selector, req.data, headers,
   1347:                           encode_chunked=req.has_header('Transfer-encoding'))
   1348:             except OSError as err: # timeout error
-->1349:                 raise URLError(err)
   1350:             r = h.getresponse()

        global URLError:  <class urllib.error.URLError>
```

After the change:
```python
Traceback (most recent call last):
  File "PYTHON_LIB:\urllib\request.py", line 1354, in do_open
       ... More lines not shown. ...
  File "PYTHON_LIB:\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "PYTHON_LIB:\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TESTS:\runtime\test_os_error.py", line 8, in test_Urllib_error
    request.urlopen("http://does_not_exist")
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

An exception of type `URLError` is a subclass of `OSError`.
An `OSError` exception is usually raised by the Operating System
to indicate that an operation is not allowed or that
a resource is not available.

I suspect that you are trying to connect to a server and
that a connection cannot be made.

If that is the case, check for typos in the URL
and check your internet connectivity.

Exception raised on line 8 of file TESTS:\runtime\test_os_error.py.

   5: def test_Urllib_error():
   6:     from urllib import request, error
   7:     try:
-->8:         request.urlopen("http://does_not_exist")
   9:     except error.URLError as e:

        request:  <module urllib.request> from PYTHON_LIB:\urllib\request.py
        request.urlopen:  <function urlopen>
```

What I did is to remove any code from within Python's standard library in the "cleaned up" traceback.
More details available at https://github.com/friendly-traceback/friendly-traceback/issues/46
