### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly#234]
Bonjour André,

Today we found a new unhandled exception:

```
## Exception Python


    :::pytb
    Traceback (most recent call last):
      File "CWD:/solution.py", line 10, in flatten
        j=int(i)
    ValueError: invalid literal for int() with base 10: ''



Une exception `ValueError` indique qu'une fonction ou une opération
a reçu un argument du bon type, mais une valeur inappropriée.



Aucune information n’est disponible au sujet de cette exception.
Veuillez signaler cet exemple à
https://github.com/aroberge/friendly/issues

Si vous utilisez la console Friendly, utilisez `www()` pour
faire une recherche sur Internet pour ce cas particulier.



### Exception levée à la ligne 10 du fichier CWD:/solution.py.



    :::text
            8: 	for i in (c_list.split(",")):
            9: 		#print(i)
        -->10: 		j=int(i)
                   ^^^^^^
           11: 		#if (i):



    :::text
        i:  ''
        int:  <class int>


```

I think it could be explained in the lines:

> `int()` expect your value to look like a number in base {base}, but you gave it ''.

or better with a special case of empty string ? "you gave it an empty string"?

I'm trying to avoid calling `int` a function or a classe in the sentence: many newcomers think this is a function, many Python developer know it is a classe, better not add trouble by using "the wrong" term.

**Comment by aroberge** [comment]
Bonjour Julien,

Thanks for the report.

I have had this one on the back-burner for a while: https://github.com/aroberge/friendly/blob/ccefcf572032ea03f3596d353b9518d1794cd6d2/friendly/runtime_errors/value_error.py#L126-L144

I started working on it, then realized that I wanted to take care of all potential bases (from 2 to 36), giving specific hints at the allowed values, and ran out of steam. 

I'll try to take care of the most common case (base 10) later today.

**Comment by aroberge** [comment]
In your example above, it looked to me like the `^^^^^` were not alligned properly with the code causing the problem. So, I did a similar test to confirm that they were indeed aligned properly.. However, I saw the following:
```
       1: # Trying to see how friendly formats the output
       2: for i in ['a', 'b', 'c']:
    -->3:     j = int(i)
                  ^^^^^^



:::text
    i:  'a'
    int:  <class int>
```
I'm wondering why  `:::text` is shown; I suspect that it should be hidden/removed

**Comment by aroberge** [comment]
New version 0.3.141 uploaded to PyPI which should contain a satisfactory explanation for this and similar cases.  I still have to write unit tests for it.

Aside: given that you use your own formatter, you might possibly be interested in issue #236.

**Comment by JulienPalard** [comment]
The `:::text` comes from my [own Markdown renderer](https://github.com/JulienPalard/correction-helper/blob/5773abbec8fbcbf0025742380f5449a050cb1340/correction_helper.py#L250), I just fixed it, thanks for the heads up.

I still can reproduce the issue of the shifted `^^^` marker with the following example:
```python
def flatten(a_list):
        a_list = repr(a_list)
        new_list = []
        for i in (a_list.split(",")):
                if not i == " ":
                        new_list.append(int(i))
        return new_list


flatten([])
```

Please note it exclusively uses tabs, not 4 spaces, sha1sum of the file is `5cdf89e740baa5c6e1c0f8b8856031726f71cdaf`, you can find it raw at `https://mdk.fr/x/u.py`. I hate tabs.

```text
$ python -m friendly u.py 

╭───────────────────────────────────────────────────────────────────────── Traceback ─────────────────────────────────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                                                                          │
│   File "HOME:/clones/JulienPalard/correction-helper/u.py", line 10, in <module>                                                                             │
│     flatten([])                                                                                                                                             │
│   File "HOME:/clones/JulienPalard/correction-helper/u.py", line 6, in flatten                                                                               │
│     new_list.append(int(i))                                                                                                                                 │
│ ValueError: invalid literal for int() with base 10: '[]'                                                                                                    │
│                                                                                                                                                             │
│ A ValueError indicates that a function or an operation received an argument of the right type, but an inappropriate value.                                  │
│                                                                                                                                                             │
│ '[]' is an invalid argument for int() in base 10. In base 10, int() is most often use to convert a string containing the digits 0 to 9 into an integer.     │
│                                                                                                                                                             │
│ Execution stopped on line 10 of file 'HOME:/clones/JulienPalard/correction-helper/u.py'.                                                                    │
│                                                                                                                                                             │
│         8:                                                                                                                                                  │
│         9:                                                                                                                                                  │
│     -->10: flatten([])                                                                                                                                      │
│                                                                                                                                                             │
│     flatten:  <function flatten>                                                                                                                            │
│                                                                                                                                                             │
│ Exception raised on line 6 of file 'HOME:/clones/JulienPalard/correction-helper/u.py'.                                                                      │
│                                                                                                                                                             │
│        4:   for i in (a_list.split(",")):                                                                                                                   │
│        5:       if not i == " ":                                                                                                                            │
│     -->6:           new_list.append(int(i))                                                                                                                 │
│                              ^^^^^^                                                                                                                         │
│        7:   return new_list                                                                                                                                 │
│                                                                                                                                                             │
│     i:  '[]'                                                                                                                                                │
│     int:  <class int>                                                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by aroberge** [comment]
I hate tabs too.   Other than TabError cases, I will probably consider all tab-related issues as "won't fix" ... for now, anyway.

If you want to reduce the number of dependencies loaded when you install "friendly", you can instead consider install "friendly-traceback" (https://github.com/friendly-traceback/friendly-traceback) which is a new project (uploaded to PyPI) and is "UI agnostic".  It should work almost as is for correction helpers, provided you replace "friendly.x by "friendly_traceback.x".

The "new" friendly will require friendly_traceback to be pip-installed, adding support for IPython, Jupyter, etc., everything that can make use of Rich (https://github.com/willmcgugan/rich).

I've started the work on friendly_idle, which also uses friendly_traceback, with no added Rich-based code.

Finally: are you happy with the explanation for this ValueError for int() ?

**Comment by JulienPalard** [comment]
> will probably consider all tab-related issues as "won't fix" ... for now, anyway.

Works for me.

> If you want to reduce the number of dependencies loaded when you install "friendly", you can instead consider install "friendly-traceback" (https://github.com/friendly-traceback/friendly-traceback)

Oh thanks for the heads up, I'm trying it! Make sense to split as you're splitting, I learnt about [DDD](https://en.wikipedia.org/wiki/Domain-driven_design) yesterday and it looks like this: splitting "the internal work" and "the external interfaces".

**Comment by JulienPalard** [comment]
> Finally: are you happy with the explanation for this ValueError for int() ?

Yes, it should work.
